### ISSUE TITLE
Java的好少

### ISSUE THREAD

**Issue by ghost** [justjavac/free-programming-books-zh_CN#226]
Java的好少

**Comment by Honwhy** [comment]
推荐一个网站
http://ifeve.com/

**Comment by Xuanwo** [comment]
Java大神快pull~

**Comment by JiangXuanYi** [comment]
卧槽，不上班么，大家

- 发送自我的Sony Xperia™智能手机

---- 漩涡编写 ----

Java大神快pull~

---

**Comment by suixiaofeng** [comment]
上班的，能收到邮件额，话说java的pdf什么的网上应该有很多了啊

**Comment by lukeyliu** [comment]
话说看书有用吗

**Comment by JiangXuanYi** [comment]
我这只有，core java  1和2还有编程思想

- 发送自我的Sony Xperia™智能手机

---- leozhou编写 ----

上班的，能收到邮件额，话说java的pdf什么的网上应该有很多了啊

---

**Comment by JiangXuanYi** [comment]
有没有用我不知道，但我知道不看书肯定不行～

- 发送自我的Sony Xperia™智能手机

---- lukeyliu编写 ----

话说看书有用吗

---

**Comment by justjavac** [comment]
又一个”读书无用“论。

**Comment by Honwhy** [comment]
读书是好事，要坚持要连贯。

**Comment by fanyikoukouchi** [comment]
求推荐计算机基础学习书籍进入bat必备书籍名单

**Comment by ReasonDuan** [comment]
大家有时间看书吗？
