### ISSUE TITLE
mac practice

### ISSUE THREAD

**Issue by i5ting** [justjavac/free-programming-books-zh_CN#238]
https://github.com/i5ting/awesome-mac-practice

**Comment by mrmign** [comment]
@i5ting  你提的这个链接 已经 `DMCA`了，你自己的repo为什么要DMCA呢？

**Comment by justjavac** [comment]
@i5ting DMCA

**Comment by i5ting** [comment]
https://github.com/i5ting/awesome-mac-practice2

**Comment by i5ting** [comment]
https://github.com/i5ting/awesome-mac-practice2
