### ISSUE TITLE
推荐《Netty 4.x 用户指南》

### ISSUE THREAD

**Issue by waylau** [justjavac/free-programming-books-zh_CN#279]
Netty 4.x 用户指南   https://github.com/waylau/netty-4-user-guide

Netty  Java  NIO  客户端服务器框架，使用它可以快速简单地开发网络应用程序，比如服务器和客户端的协议。Netty 大大简化了网络程序的开发过程比如 TCP 和 UDP 的 socket 服务的开发。

建议分类： JAVA  ,WEB 服务器

**Comment by justjavac** [comment]
自己本地修改一下，然后pull request吧。最近我比较懒。:smile:
