### ISSUE TITLE
希望可以 建立视频分享

### ISSUE THREAD

**Issue by Mr1028** [justjavac/free-programming-books-zh_CN#311]
有很多视频。。。。接近3T了。。。。

**Comment by tolerious** [comment]
下载的？

**Comment by Xuanwo** [comment]
不建议分享自己没有版权的视频，可能会遇到法律纠纷。
据我所知，这种行为也是违反Github的Tos的行为。
这并不是国内，所以请谨慎。

**Comment by Mr1028** [comment]
Think you......  以前买过 很多视频 ，大约有3T，都是一些培训机构的，基本包括大部分语言。。。。。放着也没用，想给需要的人。

**Comment by kokdemo** [comment]
毕竟这个repo是 free-programming-books，视频还是算了吧

**Comment by Mr1028** [comment]
好吧。。。。
