### ISSUE TITLE
在你身边,为你设计:腾讯的用户体验设计之道(全彩).pdf

### ISSUE THREAD

**Issue by L-movingon** [justjavac/free-programming-books-zh_CN#313]
# 在你身边,为你设计:腾讯的用户体验设计之道(全彩).pdf
[百度网盘](http://pan.baidu.com/wap/link?uk=3694234608&shareid=861544221&third=0)

**Comment by kokdemo** [comment]
呃……你这是盗版书？

**Comment by L-movingon** [comment]
这个不清楚喔  我之前下的 但好像腾讯那边已经不出了吧 (不知道, 如果是盗版的话就不要放了~ ) - -

2015-04-30 9:29 GMT+08:00 kok liu <notifications@github.com>:
