### ISSUE TITLE
高性能的JavaScript

### ISSUE THREAD

**Issue by L-movingon** [justjavac/free-programming-books-zh_CN#314]
[百度网盘](http://pan.baidu.com/s/1i3pbSzF)

**Comment by justjavac** [comment]
有在线版吗？

**Comment by L-movingon** [comment]
好像没有喔 `~

**Comment by justjavac** [comment]
这个由版权吗？

**Comment by L-movingon** [comment]
我们不是用来商用的, 用来学习的 应该不会有什么问题吧

**Comment by sleelily** [comment]
不要替作者做决定啊，人家写本书也不容易

**Comment by L-movingon** [comment]
嗯嗯~ :disappointed_relieved:

**Comment by JiangXuanYi** [comment]
我就是一个冒泡的

- 发送自我的Sony Xperia™智能手机

---- Jason Liao编写 ----

嗯嗯~ :disappointed_relieved:

---
