### ISSUE TITLE
能不能分一下级？入门，基础，高级，专家，大师等等

### ISSUE THREAD

**Issue by qiansen1386** [justjavac/free-programming-books-zh_CN#32]
@justjavac 大哥在SegementFault上的回答提醒了，像我这样的菜鸟。于是就想看看有木有打基础的书。偏重基础语言C，或者偏重基本功，比如算法与数据结构，还有设计范式，软件工程等等方面的书。
我上的学校（国外的），教学偏向于应用，基础则非常薄弱，说来惭愧，我连指针是什么都是自己Google的。这样应该可以算基础类吧。
高级可能可以加入一些，Git的高级用法之类的东东？
大师级可能是一些计算机科学的哲学领域的东东，比如一些经典中的经典的设计思路，比如Unix等。
这段时间不停地在学SQL，PHP开发框架之类的东西，真心觉得基础是最大的掣肘。再次感谢Justjavac大哥。

**Comment by Xuanwo** [comment]
弱弱问下，那个插件的进展如何？

**Comment by justjavac** [comment]
@Xuanwo What? :question:

**Comment by Xuanwo** [comment]
> 
我正在做一个 Chrome 插件，可以抓取其它网站的书评信息，整合到一起。这个周末应该可以完成。

我是指这个~

**Comment by nitta-honoka** [comment]
个人感觉分为『入门』『全面』『进阶』三个层次就行了，层次分多了容易增加选择成本，而且层次越多，如何划分的分歧就越大。

**Comment by ywh10114** [comment]
您好，请问您有时间吗？我想问问关于网页前端一些状况，请问您平时喜欢用那种联系方式
