### ISSUE TITLE
推介一个优质博客  Way Lau's Personal Site http://www.waylau.com/

### ISSUE THREAD

**Issue by waylau** [justjavac/free-programming-books-zh_CN#322]
推介一个优质博客  [Way Lau's Personal Site](http://www.waylau.com/)

**Comment by justjavac** [comment]
不知道谁添加了这么一个分类。我觉得还是去掉比较好。个人技术博客太多了，这种东西，见仁见智。

**Comment by hoosin** [comment]
对的，就比如，我喜欢看池建强，你喜欢看阮一峰。
