### ISSUE TITLE
可以添加一个“云计算”类别把 Docker 的书籍移至其中吗？

### ISSUE THREAD

**Issue by hacpai** [justjavac/free-programming-books-zh_CN#328]

**Comment by x5lcfd** [comment]
没必要

**Comment by hoosin** [comment]
没必要

**Comment by henry-zhuang** [comment]
@x5lcfd @hoosin 可是 Docker 分在“操作系统”下不合适。

**Comment by x5lcfd** [comment]
>Docker is an open-source project that automates the deployment of applications inside software containers, by providing an additional layer of abstraction and automation of operating-system-level virtualization on Linux. Docker uses resource isolation features of the Linux kernel such as cgroups and kernel namespaces to allow independent "containers" to run within a single Linux instance, avoiding the overhead of starting and maintaining virtual machines.
--- From Wikipedia.

PS: 没人说 Docker 只能应用在云计算方面.

**Comment by henry-zhuang** [comment]
@x5lcfd 是的，`Docker is an open-source project that automates the deployment of applications inside software containers` 为云计算平台提供了新的产品部署方式。

**Comment by justjavac** [comment]
虚拟化？

**Comment by lushl9301** [comment]
个人感觉 虚拟化 更好一些

今后可能还有LXC，hypervisor，microkernel的加入吧？
docker虽然没有硬件方面的虚拟，但对于文件系统的虚拟应该也算虚拟化了吧。。。
囧。。

**Comment by henry-zhuang** [comment]
@justjavac @lushl9301 其实是想添加这本书，这本书讲的是云

https://inthecloud.readthedocs.org/zh_CN/latest/posts/ch01.html
