### ISSUE TITLE
可否加一些公开课中文化项目？

### ISSUE THREAD

**Issue by myd7349** [justjavac/free-programming-books-zh_CN#333]
比如这个：
[《计算机程序的构造和解释》公开课中文化项目。](https://github.com/DeathKing/Learning-SICP)

**Comment by myd7349** [comment]
稍后添加：
[C++ Template 进阶指南](https://github.com/wuye9036/CppTemplateTutorial)

**Comment by myd7349** [comment]
已添加。

**Comment by justjavac** [comment]
已merge
