### ISSUE TITLE
《GNU make 指南》 乱码 和 《GNU make中文手册 》Not found

### ISSUE THREAD

**Issue by henry-zhuang** [justjavac/free-programming-books-zh_CN#334]
《GNU make 指南》
http://docs.huihoo.com/gnu/linux/gmake.html

《GNU make中文手册 》
http://www.yayu.org/book/gnu_make/

**Comment by CherrySD** [comment]
《GNU make 指南》是GBK编码，要在浏览器里边选一下，如果Unicode编码，自然看着就是乱的
