### ISSUE TITLE
Make 指南链接可能已经过期

### ISSUE THREAD

**Issue by zhaorui** [justjavac/free-programming-books-zh_CN#338]
当我访问 [GNU make 中文手册](http://www.yayu.org/book/gnu_make/) 的时候, 页面已经不在。

访问[GNU make 指南](http://docs.huihoo.com/gnu/linux/gmake.html) 时候， 乱码依旧存在，需要调整为GB2312 方可阅览

**Comment by seisman** [comment]
GNU make 中文手册: http://hacker-yhj.github.io/resources/gun_make.pdf
