### ISSUE TITLE
推荐一下Android-Blogs

### ISSUE THREAD

**Issue by HanderWei** [justjavac/free-programming-books-zh_CN#346]
[Android-Blogs](https://github.com/HanderWei/Android-Blogs) -- Android开发相关的博客、文章、教程

可能算不上书籍吧...总结了很多开发过程中的知识点和文章。 @justjavac

**Comment by justjavac** [comment]
我给你放到我的另一个repo吧。https://github.com/justjavac/awesome-awesomeness-zh_CN
