### ISSUE TITLE
建议开启gh-pages，并使用travis-ci进行自动构建

### ISSUE THREAD

**Issue by Xuanwo** [justjavac/free-programming-books-zh_CN#355]
http://siberiawolf.com/free_programming/index.html
这个页面很赞但是更新并不及时，太依赖于人工。
建议开启一个自己的gh-pages，并且使用travis-ci进行自动构建，免去人工的依赖，而且也能够与更新频繁的md文档进行同步。

**Comment by justjavac** [comment]
这个页面不是我做的，不过，他居然在网页里没有提到我😓

**Comment by hoosin** [comment]
我搞不懂为什么那么多人喜欢在网页上看，markdown 用来记录完全足够了。

btw @justjavac 他不注明出处，我替你杀了他吧。XD

**Comment by justjavac** [comment]
@hoosin 交给你了

**Comment by Xuanwo** [comment]
做成一个网页的话能让更多人收益吧，不过话说回来，不上github的人多半也不是目标读者群。。

**Comment by siberiawolf** [comment]
@justjavac 抱歉。之前网页中添加了出处，后来删掉了。改成了只在github中显示。

**Comment by siberiawolf** [comment]
@Xuanwo 网站已经更新。不过你提到的自动构建我不太了解，有时间的话瞅瞅，网站更新也会及时！

**Comment by Xuanwo** [comment]
过两天我写一个PR给你吧~

**Comment by AlphaHinex** [comment]
Hi @Xuanwo ，用 travis-ci 自动构建 gh-pages 听起来 sooooo cool，有实际的例子或相关资料吗？

**Comment by Xuanwo** [comment]
https://github.com/Xuanwo/xuanwo.github.io 和 https://github.com/Xuanwo/CLIWiki 都是这样构建的~

**Comment by AlphaHinex** [comment]
@Xuanwo 3Q，过程基本了解，push 权限是如何给的能简单说说吗？这样做了后提交的权限是不是任何人都能获取到了？

**Comment by Xuanwo** [comment]
你可以参考一下这个： https://xuanwo.org/2015/02/07/Travis-CI-Hexo-Autodeploy/

原理基本上就是将密钥进行二次加密，然后使用Travis CI调用~

**Comment by AlphaHinex** [comment]
嗯，谢谢。

Travis CI 现在可以设置环境变量，可以将敏感数据如 [personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) 设置到环境变量里，感觉比 SSH Key 的方式简单些

参考 https://github.com/mysterycommand/my-new-everything/blob/master/.travis.yml

**Comment by Xuanwo** [comment]
理解，不过懒得更新自己的tools chain了，就没有折腾~
