### ISSUE TITLE
tmux:高效的全键盘开发工具

### ISSUE THREAD

**Issue by aqua7regia** [justjavac/free-programming-books-zh_CN#358]
[https://github.com/aqua7regia/tmux-Productive-Mouse-Free-Development_zh](https://github.com/aqua7regia/tmux-Productive-Mouse-Free-Development_zh)

**Comment by aqua7regia** [comment]
这本书由于DMCA（数字千年版权法案）被下架，现已在GitHub删除该项目，如有需要可以邮件联系我。

**Comment by justjavac** [comment]
DMCA 23333

**Comment by aqua7regia** [comment]
您可以删了它，抱歉。

**Comment by ly0** [comment]
还没看到就下架了，好伤心

**Comment by justjavac** [comment]
已经把链接删除了

**Comment by aqua7regia** [comment]
谢谢。
