### ISSUE TITLE
建议添加 [H2 Database 教程](https://github.com/waylau/h2-database-doc)

### ISSUE THREAD

**Issue by waylau** [justjavac/free-programming-books-zh_CN#369]
[H2 Database 教程](https://github.com/waylau/h2-database-doc)

建议分类： JAVA , 数据库
描述：《H2 Database 教程》是关于  [H2 Database Engine](http://www.h2database.com) 的一个中文教程。H2 是一款短小精干的 Java 内存数据库,性能强劲。至今为止，H2 的最新版本为 Version 1.4.188 (2015-08-01), Beta。插入配图，图文并茂方便用户理解，带你快速掌握 H2。本书利用业余时间编写,由于时间紧凑,精力和能力有限,书中未免有纰漏和错误,望读者能够热忱斧正。可以在<https://github.com/waylau/h2-database-doc/issues>提供意见。

**Comment by justjavac** [comment]
点进去，怎么都是空的？

**Comment by waylau** [comment]
@justjavac  不会控啊。~目录还在整理中。但大部分内容是有的。
