### ISSUE TITLE
《计算机程序的构造和解释》不属于编译原理

### ISSUE THREAD

**Issue by DeathKing** [justjavac/free-programming-books-zh_CN#404]
将 SICP 分到编译原理下面过于狭义了。我跟倾向于将本书看做是讲授程序设计的方法论，是对程序员基本职业素养的培养（抽象）。

推荐分类：
- 程序员基本素养
- 程序设计入门基础
- 程序设计方法学
- 控制复杂度技术（软件工程）
- DSL设计方法学

ref：
- [《计算机程序的构造和解释（SICP）》讨论的核心问题是什么？ - DeathKing 的回答 - 知乎](http://www.zhihu.com/question/26549715/answer/34336593)

**Comment by L-Jovi** [comment]
:smile:  looks pretty comment ..

**Comment by wizardforcel** [comment]
属于编程思想吧。

只不过oo的编程思想叫“设计模式"，fp的编程思想还没个名字。

**Comment by lixujia** [comment]
归到文化里面去吧，虽然说这个书在MIT是编程入门教材，但是国内学这个入门的应该没有吧。
而且除了有些时间，而且对计算机文化很感兴趣的人，基本不会读这个书吧。
总之我觉得不应该放在教材里面。

**Comment by ly0** [comment]
就Lisp语言特性来说分到编译原理里也不为过吧

**Comment by AntiMoron** [comment]
建议干脆删除这一书籍以消除纠结点。
