### ISSUE TITLE
建议添加 [《NW.js 入门指南》](https://github.com/waylau/nwjs-demos)

### ISSUE THREAD

**Issue by waylau** [justjavac/free-programming-books-zh_CN#412]
建议添加 

[《NW.js 入门指南》](https://github.com/waylau/nwjs-demos)

## 简介 

[NW.js](http://nwjs.io/) （原名 node-webkit）是一个基于 `Chromium` 和 `node.js` 的应用运行时，通过它可以用  HTML 和 JavaScript 编写原生应用程序。它还允许您从 DOM 调用 [Node.js](https://nodejs.org) 的模块 ，实现了一个用所有 Web 技术来写原生应用程序的新的开发模式。

这里是[使用 NW.js 的应用和公司列表](https://github.com/nwjs/nw.js/wiki/List-of-apps-and-companies-using-nw.js)，可以看到 NW.js 实际应用效果。

## 功能特性

* 用现代 HTML5,CSS3,JS 和 WebGL 来编写应用程序。
* 完全支持 [Node.js APIs](https://nodejs.org/api/) 和所有其 [第三方模块](https://www.npmjs.com/).
* 良好的性能:Node 和 WebKit 运行在相同的线程:函数调用是更简洁;对象在同一堆可以互相引用;
* 容易打包和分发应用程序。
* 支持 Linux、Mac OS X 和 Windows

## 建议分类

Node.js 、  NW.js

**Comment by justjavac** [comment]
自己提交一下吧

**Comment by waylau** [comment]
暂未完成，不推介先
