### ISSUE TITLE
数据结构及算法

### ISSUE THREAD

**Issue by yysniper** [justjavac/free-programming-books-zh_CN#465]
没有看到该类的内容呀，希望能有

**Comment by Prince-Agrawal** [comment]
Program to construct Binary Tree and Its methods
[Binary tree.txt](https://github.com/justjavac/free-programming-books-zh_CN/files/3701001/Binary.tree.txt)

**Comment by Prince-Agrawal** [comment]
If you have any questions please ask to me.......
