### ISSUE TITLE
《DB2 教程》https://github.com/waylau/db2-tutorial

### ISSUE THREAD

**Issue by waylau** [justjavac/free-programming-books-zh_CN#469]
《DB2 教程》https://github.com/waylau/db2-tutorial

分类：数据库

简介：DB2 Tutorial 是一本关于 DB2 的开源书。截至目前，DB2 最新版本为 10.5 。利用业余时间写了本书，图文并茂，用大量实例带你一步一步走进 DB2 的世界。

**Comment by justjavac** [comment]
pr
