### ISSUE TITLE
删除不完整且许久未更新的资料

### ISSUE THREAD

**Issue by wuzhouhui** [justjavac/free-programming-books-zh_CN#485]
有许多资料未翻译完成, 而且很久没有更新过了 (比如 svn 手册, Linux Documentation (中文版)), 建议把它们删除, 是时候做个清理了, 最好再定个规矩, 只要是未完成的文档, 都不收录.

**Comment by theJian** [comment]
确实有好多过时的, 或者未完成的资料, 不过一刀切似乎不太妥当, 我提议这样, 在资料前打上标签, 比如还在译制的资料前打上 `[In Progress]`, 过时的资料打上 `[Outdated]`

**Comment by theJian** [comment]
大家可以讨论一下制订一下标准, 统一资料状态对应的标签

| 状态 | 标签 |
| --- | --- |
| 过时 | Outdated |
| 正在翻译/编纂 | In Progress |

**Comment by wuzhouhui** [comment]
同意楼上

**Comment by justjavac** [comment]
好的
