### ISSUE TITLE
可不可以在增加一下python模块介绍

### ISSUE THREAD

**Issue by gaoxinge** [justjavac/free-programming-books-zh_CN#499]
可不可以在增加一下python模块介绍，比如：

- 数据分析

   - scikit-learn

[scikit-learn官网](http://scikit-learn.org/stable/)
[scikit-learn的github](https://github.com/scikit-learn/scikit-learn) 
这是一个机器学习的库，它的官网上有机器学习的分类，以及对应类别中怎么使用scikit-learn，其本身就是机器学习的一个相当棒的资料

- 爬虫框架

   - scrapy

[scrapy的官网](http://doc.scrapy.org/en/latest/intro/install.html)
[scrapy的github](https://github.com/scrapy/scrapy)

   - pyspider

[pyspider的官网](http://docs.pyspider.org/en/latest/)
[pyspider的github](https://github.com/binux/pyspider)

   - [blog](http://cuiqingcai.com/1052.html)

还有一个学python爬虫的相当棒的博客

**Comment by justjavac** [comment]
这个repo只收免费的电子书
