### ISSUE TITLE
emacs wanted

### ISSUE THREAD

**Issue by L-Jovi** [justjavac/free-programming-books-zh_CN#502]
希望有关于 emacs 的书籍  最好适用 vim 过渡来的新手 😄

**Comment by AntiMoron** [comment]
你这个叛教的传道者。

**Comment by nmter** [comment]
- -

**Comment by HuanGong** [comment]
都用vim了，为什么还过度到emacs....

**Comment by shenlongxing** [comment]
叛徒

**Comment by theJian** [comment]
因为 vimscript 实在是太烂了

**Comment by robturtle** [comment]
ex-vimmer 转 emacs 当然是去看 spacemacs 官方文档就好了啊

**Comment by ly0** [comment]
@theJian 又不是不可以用python写

**Comment by L-Jovi** [comment]
。。。。默默 close 掉  不然本喵会被踩死 = =

**Comment by L-Jovi** [comment]
喵的 gnu 的文档跟看圣经似的 。。 继续求中文书籍  :)

**Comment by AntiMoron** [comment]
屌。 你要是♀我可以手把手教你读圣经。

**Comment by L-Jovi** [comment]
@AntiMoron  。。少年  去好好找个女朋友吧  。。本喵是公的 。。

**Comment by AntiMoron** [comment]
@L-Jovi   ...女朋友我有了啊、肛好缺个男朋友

**Comment by L-Jovi** [comment]
@AntiMoron  。。。。。。

**Comment by diql** [comment]
@L-Jovi @AntiMoron 两位好登对的头像

**Comment by tony1016** [comment]
哈哈哈

**Comment by alexinea** [comment]
前排围观如何歪楼中。

**Comment by leeleoo** [comment]
说好的同性交友网站呢

**Comment by YouthLin** [comment]
后排火钳刘明

**Comment by wizardforcel** [comment]
表示前来围观。

**Comment by Yven** [comment]
可以，很强势。擦♂出了爱情的火花

**Comment by stonewangbo** [comment]
赶紧围观

**Comment by GerBawn** [comment]
车要开了，快上车

**Comment by wujunze** [comment]
带上小板凳   围观

**Comment by Sijiu** [comment]
你们这样真的好吗？

**Comment by liguangsheng** [comment]
虽然我用emacs，但是我也挺喜欢vim的

**Comment by wonsikin** [comment]
瓜子，啤酒，香烟...这位乘客，麻烦让一下

**Comment by EdisonHe** [comment]
你们继续

**Comment by jouhns** [comment]
前排围观

**Comment by wangwei10061** [comment]
来啊来啊，正面gang啊，谁怕谁

**Comment by weberxie** [comment]
Lol

**Comment by Jetman13** [comment]
从群里传送过来的Q_Q

**Comment by Prometheuscx** [comment]
以为会发生点什么

**Comment by sablib** [comment]
观光团

**Comment by sky-mxc** [comment]
up

**Comment by ProcessorSong** [comment]
强势围观

**Comment by SOULSSH** [comment]
火速围观

**Comment by numbcoder** [comment]
![](http://ww1.sinaimg.cn/mw690/6f1140e5jw1ey6ia4r1p5g206e05jjs0.gif)

**Comment by YouthLin** [comment]
楼上的各位道友，你们是从哪来的观光团？

**Comment by Lich2013** [comment]
🌚

**Comment by dongyado** [comment]
都是从v2ex来的

**Comment by Vikinglei** [comment]
What? 这是百度贴吧？是不是走错了传送门？

**Comment by jiangzhouq** [comment]
v2ex大军哈哈哈哈哈哈

**Comment by jouhns** [comment]
qqq群观光团

**Comment by YouthLin** [comment]
@jouhns 求群号

**Comment by zzcv** [comment]
v2前排围观下

**Comment by riverxing** [comment]
qq群观光组

**Comment by songdehuai** [comment]
qq群观光团

**Comment by SpecialCyCi** [comment]
v2ex 观肛团

**Comment by lqccan** [comment]
v2观光团

**Comment by chaegumi** [comment]
v2ex 观肛团

**Comment by weberxie** [comment]
互粉么？

**Comment by zcl0621** [comment]
v2ex 观光团

**Comment by Mr-LiZL** [comment]
带上小板凳,我就静静的观肛

**Comment by zhangzheyuk** [comment]
v2ex刚肛团撸过

**Comment by Karblue** [comment]
观光团路过

**Comment by qianbin** [comment]
v2ex 观光团

**Comment by songdehuai** [comment]
557951370，新群有来的吗现在还没人。

**Comment by justjavac** [comment]
225932282 【github千人交流群】@yanhaijing 大大的群 http://jq.qq.com/?_wv=1027&k=2H2XAO6

**Comment by Bittree** [comment]
我擦，强势围观

**Comment by tony1016** [comment]
受不了了，一堆邮件提醒，退

**Comment by onestarshang** [comment]
火钳刘明

**Comment by Prometheuscx** [comment]
邮箱炸了

**Comment by vivian8725118** [comment]
到底在干什么。。。邮箱要炸掉了

**Comment by justjavac** [comment]
@Prometheuscx @vivian8725118 把邮箱提醒关闭

**Comment by hoosin** [comment]
辣鸡。

**Comment by magicdawn** [comment]
Atom 大法好

**Comment by Runpop** [comment]
Atom大法好

**Comment by jiaojie1989** [comment]
v2ex 观光团 路过

**Comment by faluo116** [comment]
从V2过来观光。为什么都没有人提到微软的那个vsCode

**Comment by scofieldpeng** [comment]
v2观光团，sb,vscode,atom那么多，不要再一棵树上吊死，哈哈哈

**Comment by iURWang** [comment]
不明真相的围观群众

**Comment by yanhaijing** [comment]
sublime 大法好

**Comment by camilesing** [comment]
V站大军抵达

**Comment by qex** [comment]
德玛西亚！只有 PICO 才是正义！其他都是邪道！

**Comment by qex** [comment]
德玛西亚！只有 PICO 才是正义！其他都是邪道！

**Comment by qex** [comment]
德玛西亚！只有 PICO 才是正义！其他都是邪道！

**Comment by Mark24Code** [comment]
v2观光团
Sublime大法好
![Alt Text](http://ww1.sinaimg.cn/small/44894cbbgw1f4xaq4yz9wj204403omx1.jpg)

**Comment by magichan** [comment]
V2ex  小货车
Vim 旗帜不能倒

**Comment by ShinCurry** [comment]
不是很懂你们用 emacs 的人。

**Comment by cstopery** [comment]
baby in vim car

**Comment by yougg** [comment]
## `果然全球最大同性交友网站`
![同性交友](http://joymepic.joyme.com/article/uploads/allimg/201601/1453796035489629.gif)

**Comment by megatontech** [comment]
![338df01f3a292df50e42642fba315c6035a873ef](https://cloud.githubusercontent.com/assets/15758369/16118662/b8a8cdd2-340a-11e6-885f-7d05612a568e.jpg)

**Comment by enjelbeteu** [comment]
@justjavac v2ex观光团

**Comment by imhu** [comment]
你们够了 - -

**Comment by wsdjeg** [comment]
block, 邮箱提醒无法关闭, 有其他通知必须要收. 所以不好意思了. 我觉得, 这样的issue 应该锁住.

**Comment by aprikyblue** [comment]
@wsdjeg 右边Notifications [Unsubscribe]

**Comment by RedL0tus** [comment]
果然全球最大同性交友网站
====================

(V2EX 观光团

**Comment by xspoco** [comment]
![60512853gw1f4x0z83ohcg206e05j0t2](https://cloud.githubusercontent.com/assets/19290455/16125915/70230faa-3428-11e6-9cec-401dbb858faf.gif)

**Comment by taozhijiang** [comment]
Close之前，火速留名！

**Comment by iosx** [comment]
v2ex司机

**Comment by DoRoll** [comment]
v2ex观光团。。。。

**Comment by wizardforcel** [comment]
终于close了哈哈哈哈。

**Comment by L-Jovi** [comment]
@justjavac  造成麻烦很抱歉  没想到求本书变成这样

**Comment by ljsalm089** [comment]
v2ex观光团

**Comment by mrxuanzhang** [comment]
v2ex 观光团

**Comment by wuwentan** [comment]
不明真相的吃瓜群众

**Comment by luy07** [comment]
V2EX 观光团

**Comment by hingsir** [comment]
不明觉厉

**Comment by Jiasm** [comment]
围观

**Comment by Vic020** [comment]
其实让别人打代码是最好的，都去做老板去吧

**Comment by misakuo** [comment]
V站观光团

**Comment by jeff-wu** [comment]
v2观光团后排围观

**Comment by yeket** [comment]
v2ex观光团~

**Comment by pikeszfish** [comment]
v2ex观光团~

**Comment by lazyphp** [comment]
听说你们吵起来了。v2ex观光团~

**Comment by yuchaozh** [comment]
你们真是够了，不好好加班还有时间刷github

**Comment by hiyelang** [comment]
v2ex观光团

**Comment by yishenggudou** [comment]
-1

**Comment by BruceLEO1969** [comment]
v2ex观光团~

**Comment by cesing** [comment]
获前六名

**Comment by Liaoer** [comment]
说好的撕B呢？瓜子都准备好了

**Comment by cedooo** [comment]
说好的撕逼呢？？楼都歪到哪里去了？

**Comment by taliu** [comment]
从来就没用过emacs....

**Comment by mmjbds999** [comment]
辣鸡啊辣鸡

**Comment by xiaochao** [comment]
默默的搬个小板凳坐下

**Comment by mokeyjay** [comment]
写PHP的话还是phpStorm大法好！写前端还是Sublime或者Atom大法好！

**Comment by dabing1022** [comment]
![](https://ss1.baidu.com/6ONXsjip0QIZ8tyhnq/it/u=3028809769,4058468768&fm=58)

_VS_

![](https://ss0.baidu.com/6ONWsjip0QIZ8tyhnq/it/u=2119654284,116273548&fm=58)

**Comment by VonFry** [comment]
讲道理。。除了脚本外，用上插件。。两个其实都差不多吧。。vim和emacs都有插件能相互模仿。。至于脚本，vim能用python能用lua能用blablablabla，emacs用lisp，其实都差不多了。。

**Comment by igaozp** [comment]
给你来点干货吧 https://github.com/emacs-tw/awesome-emacs

**Comment by igaozp** [comment]
给你来点干货吧 https://github.com/emacs-tw/awesome-emacs

**Comment by lujun9972** [comment]
21天学会Emacs
http://book.emacs-china.org/

真不明白，spacemacs出来之后，还有什么好争执的

**Comment by CAOJINGYOU** [comment]
你们聊啥呢

**Comment by wangziyu9** [comment]
我就来看看

**Comment by elloop** [comment]
微博观光团到此一游

**Comment by xxstop** [comment]
观光路过

**Comment by ZehuaJiang** [comment]
开车到此一游
