### ISSUE TITLE
可不可以推荐些CUDA编程的书籍？

### ISSUE THREAD

**Issue by Payuing** [justjavac/free-programming-books-zh_CN#515]
刚入门在学，但没有在目录下找到相关内容，是不是因为太小众？
我目前在读官方手册
https://developer.nvidia.com/cuda-gpus

**Comment by shidephen** [comment]
中文好像就那么几本

**Comment by wangxianhe** [comment]
《Professional CUDA C Programming》看这一本吧，非常详细，很厚，写的很好
