### ISSUE TITLE
Android学习之路，链接失效

### ISSUE THREAD

**Issue by jamiglee** [justjavac/free-programming-books-zh_CN#530]
http://www.stormzhang.com/android/2014/07/07/learn-android-from-rookie/

404

**Comment by jamiglee** [comment]
http://stormzhang.com/android/2014/07/07/learn-android-from-rookie/

把前面www去掉就可以了

**Comment by alexoart** [comment]
https://www.androidos.net.cn/codebook/AndroidRoad/
