### ISSUE TITLE
添加了区块链条目和书籍信息

### ISSUE THREAD

**Issue by imfly** [justjavac/free-programming-books-zh_CN#539]
区块链是目前比肩VR、大数据的三大创新技术之一，市面上系统的资料非常少，从源码级别介绍区块链的书籍更是极为少见，这里添加一本中文书籍 《Nodejs开发加密货币》 https://github.com/imfly/bitcoin-on-nodejs 供小伙伴们参考学习。

**Comment by theJian** [comment]
:+1:

**Comment by GitVishwa** [comment]
In addition to imfly comment, i got a plain explaination of block chain.

[Block Chain](https://www.linkedin.com/pulse/blockchain-explanation-your-mum-could-understand-jamie-skella)
