### ISSUE TITLE
Add readme.md transcript for English

### ISSUE THREAD

**Issue by jitendra3109** [justjavac/free-programming-books-zh_CN#569]
Huge and nice collection and also getting very much appreciated from the community.
It would be great if somebody can translate into English then it will be reaching out to global.

**Comment by Bethannfrum** [comment]
#569

**Comment by DOWNTOWNJIzMBROWN26** [comment]
So I'm having problems with my Android S7 edge. I want to learn how and who to tell when something happens.id like to know how to know fundamentals of script, where I can look at a text/script and a lot of the times will know wherevtge text is bad. IBM HAS A COGNITIVE CAREER, OPPORTUNITIES OR SOMETHING LIKE THAT. What do you think? I need to know what to do to solve my tech problems.

**Comment by ghimireadarsh** [comment]
Engish version would be so much helpful with all these contents.

**Comment by ana-nyaa** [comment]
May I work on this issue @jitendra3109

**Comment by wizardforcel** [comment]
WTF

**Comment by basanherki** [comment]
very good idea

**Comment by money473271212** [comment]
Excellent idea to translate to English

**Comment by CodeNameFox06** [comment]
i can help you...feel free to contact

**Comment by Pushmuck** [comment]
Oi oi oi

**Comment by storagedubai** [comment]
do anyone have [Self Storage Dubai](https://www.idealhomestoragedubai.com) app for [storage in dubai](https://www.idealhomestoragedubai.com), i have my site for [storage Dubai](https://www.idealhomestoragedubai.com)

**Comment by LalanaChami** [comment]
I worked on it, and add a PR

**Comment by CodeNameFox06** [comment]
ok
