### ISSUE TITLE
提供几个在线文档

### ISSUE THREAD

**Issue by alairs** [justjavac/free-programming-books-zh_CN#580]
Debian 参考手册  <http://getos.org/debian-reference/index.zh-cn.html>
Linux工具快速教程  <http://getos.org/Linux_Tools_Quick_Tutorial/index.html>
The Linux Command Line 中文版  <http://getos.org/cli/index.html>
 PHP 5 中文手册 <http://getos.org/php5_manual_zh_CN/index.html>
MySQL中文手册 <http://getos.org/mysql323/preface.htm>
Linux C语言编程  <http://getos.org/linux_and_c/index.html>
HTML手册 <http://getos.org/html_manual/index.html>
Linux From Scratch <http://getos.org/lfs_6.4_zhcn/index.html>
Linux From Scratch 7.7 systemd <http://getos.org/LFS-BOOK-7.7-systemd/index.html>
Windows程式开发设计 <http://getos.org/wpw/index.html>
开源世界旅行手册 <http://getos.org/trow/index.html>
ArchLinux安装 <http://getos.org/alinstall/index.html>
OpenSUSE安装 <http://getos.org/osinstall/index.html>
Debian7 安装 <http://getos.org/cndebian/index.html>
DOS详解 <http://getos.org/dos.html>
ngx_pagespeed使用指南 <http://getos.org/ngx_pagespeed/index.html>

**Comment by ZJUGuoShuai** [comment]
你的网站诶，不过都很不错
