### ISSUE TITLE
大数据资料太少了，链接挂了 

### ISSUE THREAD

**Issue by manymore13** [justjavac/free-programming-books-zh_CN#597]
大数据链接挂了 ,希望楼主有空可以补上

**Comment by minminaya** [comment]
大数据/数据挖掘/推荐系统/机器学习相关资源链接挂了

**Comment by Ziv-Android** [comment]
大数据/数据挖掘/推荐系统/机器学习相关资源，面向程序员的数据挖掘指南， 大型集群上的快速和通用数据处理架构的链接都挂了
