### ISSUE TITLE
PHP调试技术手册(PDF)--此书链接失效

### ISSUE THREAD

**Issue by the263** [justjavac/free-programming-books-zh_CN#640]
如题,请查证.我无法下载,提示404

**Comment by KellyHwong** [comment]
是失效了。刚找到了别的源：[PHP-Debug-Manual-public.pdf](https://blog.xiayf.cn/assets/uploads/files/PHP-Debug-Manual-public.pdf)

**Comment by Alexkho82** [comment]
#640
