### ISSUE TITLE
发现了中文版《编码宝典》

### ISSUE THREAD

**Issue by liruochen1998** [justjavac/free-programming-books-zh_CN#651]
程序员必读的非编程书籍列表中的最后一个《编码宝典》，作者注明无中文译版，今天我在浏览时发现了其中文版本，附上链接。
https://www.amazon.cn/dp/B074JS9ZZX/ref=sr_1_1?ie=UTF8&qid=1529631935&sr=8-1&keywords=%E7%BC%96%E7%A0%81%E5%AE%9D%E5%85%B8

**Comment by Alexkho82** [comment]
651
