### ISSUE TITLE
Android 目录下的很多链接失效。。。

### ISSUE THREAD

**Issue by OkamiyGit** [justjavac/free-programming-books-zh_CN#665]
比如。Android学习路线已无法访问，，还有几个也是无法连接

**Comment by zombie110year** [comment]
目前（2019-06-20）有两个链接无法访问：
Android 学习之路： http://www.stormzhang.com/android/2014/07/07/learn-android-from-rookie/
Android 6.0 新特性讲解： http://leanote.com/blog/post/561658f938f41126b2000298

前者怀疑是作者修改了博客域名，后者则可能无法找回了。
