### ISSUE TITLE
鸟哥的linux私房菜打不开了

### ISSUE THREAD

**Issue by Turifan** [justjavac/free-programming-books-zh_CN#675]
鸟哥的linux私房菜打不开了

**Comment by fanjizhu** [comment]
鸟哥的linux私房菜打不开了

**Comment by ChenHom** [comment]
[目前網址 http://cn.linux.vbird.org/](http://cn.linux.vbird.org/)

**Comment by Core00077** [comment]
我来提供一下第四版的吧，很久之前在网上找到并收藏的，不知道有没有版权问题。https://wizardforcel.gitbooks.io/vbird-linux-basic-4e/content/index.html
