### ISSUE TITLE
Python--Data-Structure-and-Algorithms

### ISSUE THREAD

**Issue by Seule-Seule** [justjavac/free-programming-books-zh_CN#678]
https://github.com/Seule-Seule/Python--Data-Structure-and-Algorithms

**Comment by sahilsinghrawat** [comment]
[Alfred V. Aho - Data Structures and Algorithms.pdf](https://github.com/justjavac/free-programming-books-zh_CN/files/2942650/Alfred.V.Aho.-.Data.Structures.and.Algorithms.pdf)
