### ISSUE TITLE
哪位同学有《JavaScript面向对象精要》吗？

### ISSUE THREAD

**Issue by zwl1619** [justjavac/free-programming-books-zh_CN#686]
哪位同学有《JavaScript面向对象精要》吗？
https://item.jd.com/11667775.html

**Comment by Crazylshao** [comment]
我有


发自我的 iPhone

**Comment by zwl1619** [comment]
@Crazylshao 是电子版吗？可以分享一下吗？

**Comment by lixuguang** [comment]
> @Crazylshao 是电子版吗？可以分享一下吗？

这本书微信阅读上有

**Comment by zwl1619** [comment]
@lixuguang 微信读书里面能搜到，但显示待上架
