### ISSUE TITLE
一堆链接失效，这个是用来搞笑的吧？

### ISSUE THREAD

**Issue by caglee** [justjavac/free-programming-books-zh_CN#720]

**Comment by zombie110year** [comment]
你发现链接失效，可以在 issue 里提出来，会有人去找有效链接或者删除记录的。

**Comment by caglee** [comment]
1.Google Java编程风格指南
2.面向程序员的数据挖掘指南
还有几个之前发现的忘记了，后面发现再补充吧

**Comment by simlePig** [comment]
编程艺术中《 取悦的工序：如何理解游戏》

**Comment by kokdemo** [comment]
建议搞一个工具定期扫描一下链接

**Comment by liuzhilinux** [comment]
其实可以搞一个工具，除了定期扫描一下链接，还可以搞一个服务器，定时爬取一下链接的数据，并保存在服务器上。

**Comment by zombie110year** [comment]
> 其实可以搞一个工具，除了定期扫描一下链接，还可以搞一个服务器，定时爬取一下链接的数据，并保存在服务器上。

扫描链接可以，但是爬取并保存数据可能涉及侵权。

**Comment by shankesgk2** [comment]
看见这个issue想骂人,失效你可以提出来.搞笑?呵呵

**Comment by sanjayzzzhong** [comment]
失效提出来不就好了

**Comment by timmmGZ** [comment]
失效肯定会有的，提出来就好了
