### ISSUE TITLE
除了免费的书籍，是否可以提交一些方便的在线工具？

### ISSUE THREAD

**Issue by zeal0214** [justjavac/free-programming-books-zh_CN#726]
收集了一些便捷的在线工具：
比如：
时间戳转换：https://unixtime.51240.com/
unicode编码转换：http://tool.chinaz.com/Tools/Unicode.aspx
文本比较：http://wenbenbijiao.renrensousuo.com/
在线画图：https://www.draw.io/
开源协议相关：http://choosealicense.online/
正则测试：http://tool.oschina.net/regex/
json校验：http://www.bejson.com/
url编码：https://www.w3school.com.cn/tags/html_ref_urlencode.html
git图解：http://marklodato.github.io/visual-git-guide/index-zh-cn.html
.........

**Comment by Linnzh** [comment]
时间戳转换：[https://tool.jisuapi.com/unixtime.html](https://tool.jisuapi.com/unixtime.html)

这类在线工具好像比较多
