### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by iPenManShip** [justjavac/free-programming-books-zh_CN#737]
**建议更改一下目录**，方便读者，我要看js的发现往下拉好久好久，而且跳转一下回来还得再拉好久如果有折叠的功能靠后的书籍应该会更方便查找吧  

![image](https://user-images.githubusercontent.com/36189354/69945649-fb755c80-1524-11ea-9774-4077b113ff9f.png)

**Comment by pifeifei** [comment]
浏览器中  ctrl +f     再输入  JavaScript
