### ISSUE TITLE
有些链接失效了呢

### ISSUE THREAD

**Issue by waconde** [justjavac/free-programming-books-zh_CN#743]
今天想看大数据下的子项，发现第一、二、三项失效了：
大数据 / 数据挖掘 / 推荐系统 / 机器学习相关资源
面向程序员的数据挖掘指南
大型集群上的快速和通用数据处理架构

**Comment by BackMountainDevil** [comment]
fork修改pull request

**Comment by zhen-aiguo** [comment]
ok


 
---原始邮件---
发件人: "Kearney"<notifications@github.com&gt;
发送时间: 2020年4月13日 16:53:47
收件人: "justjavac/free-programming-books-zh_CN"<free-programming-books-zh_CN@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [justjavac/free-programming-books-zh_CN] 有些链接失效了呢 (#743)




 
fork修改pull request
