### ISSUE TITLE
推荐learn-go-with-tests。借楼招个人

### ISSUE THREAD

**Issue by jiffies** [justjavac/free-programming-books-zh_CN#749]
字节跳动教育线新项目，大投入，千亿级市场，服务端工程师大量缺口，各级别都要。项目主要使用Golang/Python，但是语言不做要求，可以来了再学。研发直招渠道，快速反馈，支持年前面试(可以远程面试)，年后报道，北京、上海都有HC。完整简历请投邮箱 lichengqian@bytedance.com。邮件标题：在线教育+姓名

**Comment by sanjayzzzhong** [comment]
C++或者JAVA可以吗？

**Comment by jiffies** [comment]
> C++或者JAVA可以吗？

可以的，面试项目经验和基本功，语言不限

**Comment by kabukapu** [comment]
JAVA,做了两年，可独立搭建前后端，部署运维，有意向，可联系电话13013606100



在 2020-01-02 12:46:26，"Li ChengQian" <notifications@github.com> 写道：

C++或者JAVA可以吗？

可以的，面试项目经验和基本功，语言不限

**Comment by xiaokugua250** [comment]
广州有位置吗？

**Comment by kabukapu** [comment]
坐标上海，杭州



在 2020-01-02 14:47:36，"Du Liang" <notifications@github.com> 写道：

广州有位置吗？

**Comment by timmmGZ** [comment]
最近都在用python java实践AI，没有广州可惜了
