### ISSUE TITLE
scala指南链接进去是性爱指南

### ISSUE THREAD

**Issue by HJacco** [justjavac/free-programming-books-zh_CN#750]

**Comment by gky99** [comment]
看了，没有问题，应该是被dns劫持了

**Comment by timmmGZ** [comment]
而且issue评论过都有机会被外国色情邮件轰炸，题外话 不太喜欢scala的各类语法没有统一的格式规范

**Comment by wizardforcel** [comment]
23333

**Comment by huwq1987** [comment]
http://zh.scala-tour.com/ 点进去确实被跳转到了不明网站，还让我下载不明软件
煎蛋观光团hahaha
